apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: cmaestro-db
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cmaestro-db
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: db
      nodePort: 30543