apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: cmaestro-db
  labels:
    app.kubernetes.io/name: seaweedfs
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: s3
      port: 8333
      targetPort: s3
    - name: master
      port: 9333
      targetPort: master
    - name: filer
      port: 8888
      targetPort: filer
    - name: volume
      port: 9340
      targetPort: volume
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3
  namespace: cmaestro-db
  labels:
    app.kubernetes.io/name: seaweedfs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: s3
      port: 8333
      targetPort: s3
      nodePort: 30833
    - name: filer
      port: 8888
      targetPort: filer
      nodePort: 30888