# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Cmaestro/API/Builder

on:
  push:
  pull_request:

env:
  BIN_NAME: cmaestro-api
  BIN_FOLDER: bin
  PACKAGE_PATH: cmaestro-api/cmd/api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.3"

      - name: Create Build Directory
        run: mkdir $BIN_FOLDER

      - name: Build Cmaestro-API
        run: go build -v -o $BIN_FOLDER/$BIN_NAME $PACKAGE_PATH

      - name: Upload Cmaestro-API as an artifact  
        uses: actions/upload-artifact@v4
        with:
          name: $BIN_NAME
          path: $BIN_FOLDER
